/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrafficRouteImport } from './routes/admin.traffic'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminRssSourcesRouteImport } from './routes/admin.rss-sources'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminIngestRouteImport } from './routes/admin.ingest'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAdSettingsRouteImport } from './routes/admin.ad-settings'
import { Route as ApiPublicIngestRssRouteImport } from './routes/api/public/ingest-rss'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'
import { Route as AdminArticleStatsSlugRouteImport } from './routes/admin.article-stats.$slug'
import { Route as ApiPublicHooksIngestRssRouteImport } from './routes/api/public/hooks/ingest-rss'
import { Route as ApiPublicHooksCheckAdsRouteImport } from './routes/api/public/hooks/check-ads'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrafficRoute = AdminTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRssSourcesRoute = AdminRssSourcesRouteImport.update({
  id: '/rss-sources',
  path: '/rss-sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdSettingsRoute = AdminAdSettingsRouteImport.update({
  id: '/ad-settings',
  path: '/ad-settings',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicIngestRssRoute = ApiPublicIngestRssRouteImport.update({
  id: '/api/public/ingest-rss',
  path: '/api/public/ingest-rss',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticleStatsSlugRoute = AdminArticleStatsSlugRouteImport.update({
  id: '/article-stats/$slug',
  path: '/article-stats/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksIngestRssRoute = ApiPublicHooksIngestRssRouteImport.update({
  id: '/api/public/hooks/ingest-rss',
  path: '/api/public/hooks/ingest-rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckAdsRoute = ApiPublicHooksCheckAdsRouteImport.update({
  id: '/api/public/hooks/check-ads',
  path: '/api/public/hooks/check-ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/ad-settings': typeof AdminAdSettingsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/rss-sources': typeof AdminRssSourcesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/article-stats/$slug': typeof AdminArticleStatsSlugRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/public/ingest-rss': typeof ApiPublicIngestRssRoute
  '/api/public/hooks/check-ads': typeof ApiPublicHooksCheckAdsRoute
  '/api/public/hooks/ingest-rss': typeof ApiPublicHooksIngestRssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/ad-settings': typeof AdminAdSettingsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/rss-sources': typeof AdminRssSourcesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/article-stats/$slug': typeof AdminArticleStatsSlugRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/public/ingest-rss': typeof ApiPublicIngestRssRoute
  '/api/public/hooks/check-ads': typeof ApiPublicHooksCheckAdsRoute
  '/api/public/hooks/ingest-rss': typeof ApiPublicHooksIngestRssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/admin/ad-settings': typeof AdminAdSettingsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/rss-sources': typeof AdminRssSourcesRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/article-stats/$slug': typeof AdminArticleStatsSlugRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/public/ingest-rss': typeof ApiPublicIngestRssRoute
  '/api/public/hooks/check-ads': typeof ApiPublicHooksCheckAdsRoute
  '/api/public/hooks/ingest-rss': typeof ApiPublicHooksIngestRssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/admin/ad-settings'
    | '/admin/ads'
    | '/admin/categories'
    | '/admin/ingest'
    | '/admin/new'
    | '/admin/rss-sources'
    | '/admin/stats'
    | '/admin/traffic'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/'
    | '/admin/article-stats/$slug'
    | '/admin/edit/$id'
    | '/admin/users/$id'
    | '/api/public/ingest-rss'
    | '/api/public/hooks/check-ads'
    | '/api/public/hooks/ingest-rss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/admin/ad-settings'
    | '/admin/ads'
    | '/admin/categories'
    | '/admin/ingest'
    | '/admin/new'
    | '/admin/rss-sources'
    | '/admin/stats'
    | '/admin/traffic'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin'
    | '/admin/article-stats/$slug'
    | '/admin/edit/$id'
    | '/admin/users/$id'
    | '/api/public/ingest-rss'
    | '/api/public/hooks/check-ads'
    | '/api/public/hooks/ingest-rss'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/admin/ad-settings'
    | '/admin/ads'
    | '/admin/categories'
    | '/admin/ingest'
    | '/admin/new'
    | '/admin/rss-sources'
    | '/admin/stats'
    | '/admin/traffic'
    | '/admin/users'
    | '/article/$slug'
    | '/category/$slug'
    | '/admin/'
    | '/admin/article-stats/$slug'
    | '/admin/edit/$id'
    | '/admin/users/$id'
    | '/api/public/ingest-rss'
    | '/api/public/hooks/check-ads'
    | '/api/public/hooks/ingest-rss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiPublicIngestRssRoute: typeof ApiPublicIngestRssRoute
  ApiPublicHooksCheckAdsRoute: typeof ApiPublicHooksCheckAdsRoute
  ApiPublicHooksIngestRssRoute: typeof ApiPublicHooksIngestRssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traffic': {
      id: '/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AdminTrafficRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rss-sources': {
      id: '/admin/rss-sources'
      path: '/rss-sources'
      fullPath: '/admin/rss-sources'
      preLoaderRoute: typeof AdminRssSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-settings': {
      id: '/admin/ad-settings'
      path: '/ad-settings'
      fullPath: '/admin/ad-settings'
      preLoaderRoute: typeof AdminAdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/ingest-rss': {
      id: '/api/public/ingest-rss'
      path: '/api/public/ingest-rss'
      fullPath: '/api/public/ingest-rss'
      preLoaderRoute: typeof ApiPublicIngestRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/article-stats/$slug': {
      id: '/admin/article-stats/$slug'
      path: '/article-stats/$slug'
      fullPath: '/admin/article-stats/$slug'
      preLoaderRoute: typeof AdminArticleStatsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/ingest-rss': {
      id: '/api/public/hooks/ingest-rss'
      path: '/api/public/hooks/ingest-rss'
      fullPath: '/api/public/hooks/ingest-rss'
      preLoaderRoute: typeof ApiPublicHooksIngestRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-ads': {
      id: '/api/public/hooks/check-ads'
      path: '/api/public/hooks/check-ads'
      fullPath: '/api/public/hooks/check-ads'
      preLoaderRoute: typeof ApiPublicHooksCheckAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAdSettingsRoute: typeof AdminAdSettingsRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIngestRoute: typeof AdminIngestRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminRssSourcesRoute: typeof AdminRssSourcesRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminTrafficRoute: typeof AdminTrafficRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticleStatsSlugRoute: typeof AdminArticleStatsSlugRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdSettingsRoute: AdminAdSettingsRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIngestRoute: AdminIngestRoute,
  AdminNewRoute: AdminNewRoute,
  AdminRssSourcesRoute: AdminRssSourcesRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminTrafficRoute: AdminTrafficRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticleStatsSlugRoute: AdminArticleStatsSlugRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiPublicIngestRssRoute: ApiPublicIngestRssRoute,
  ApiPublicHooksCheckAdsRoute: ApiPublicHooksCheckAdsRoute,
  ApiPublicHooksIngestRssRoute: ApiPublicHooksIngestRssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
